# Base Configuration for Research Assistant AI Agent
# This file contains default settings that can be overridden by environment-specific configs

# API Configuration
api:
  openai:
    model: "gpt-4"
    max_tokens: 4000
    temperature: 0.7
    timeout: 30
    max_retries: 3
    backoff_factor: 2
  
  huggingface:
    enabled: true
    cache_dir: "./models/huggingface"
    max_models_cached: 5
    timeout: 60

# Database Configuration
database:
  mongodb:
    database_name: "research_assistant"
    collection_name: "arxiv_papers"
    vector_index: "vector_search_index"
    connection_timeout: 10
    max_pool_size: 100
    retry_writes: true
  
  bigquery:
    dataset_id: "research_data"
    table_id: "paper_analysis"
    location: "US"

# Agent Configuration
agents:
  search:
    max_papers_per_search: 5
    similarity_threshold: 0.7
    vector_dimensions: 768
    
  hypothesis:
    max_iterations: 3
    confidence_threshold: 0.8
    min_hypothesis_length: 100
    max_hypothesis_length: 1000
    
  code:
    enable_huggingface: true
    validation_timeout: 30
    max_complexity_score: 10
    enable_spell_check: true
    enable_execution: true
    execution_timeout: 60
    
  visualization:
    output_dpi: 300
    style: "scientific"
    chart_width: 12
    chart_height: 8
    save_format: "png"
    
  report:
    default_style: "arxiv"
    include_appendix: true
    max_paper_length: 15000
    citation_style: "APA"
    export_formats: ["txt", "html", "latex"]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "logs/research_agent.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
    - type: "console"
      level: "INFO"
  
  # Structured logging for analytics
  structured_logging:
    enabled: true
    format: "json"
    fields: ["timestamp", "level", "agent", "action", "duration", "status"]

# Performance Configuration
performance:
  max_concurrent_agents: 5
  request_timeout: 120
  cache_ttl: 3600  # 1 hour
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
  memory:
    max_memory_usage: "512MB"
    gc_threshold: "400MB"

# Security Configuration
security:
  api_key_rotation_days: 90
  log_sensitive_data: false
  encrypt_outputs: false
  allowed_file_types: ["txt", "html", "tex", "pdf", "png", "jpg"]
  max_file_size: "50MB"

# Output Configuration
output:
  base_directory: "generated_papers"
  filename_template: "{query_hash}_{timestamp}"
  backup_enabled: true
  cleanup_after_days: 30
  
  paper_settings:
    font_family: "Times New Roman"
    font_size: 12
    line_spacing: 1.5
    margin: "1 inch"
    
# Human-in-the-Loop Configuration
human_in_loop:
  enabled: true
  approval_required_stages: ["hypothesis", "code", "visualization", "report"]
  timeout_seconds: 300
  default_approval: false  # Require explicit approval
  
# Monitoring Configuration
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  error_reporting: true
  health_check_interval: 60
  
  alerts:
    error_threshold: 10  # errors per hour
    latency_threshold: 30  # seconds
    memory_threshold: 80  # percentage

# Development Configuration
development:
  debug_mode: false
  verbose_logging: false
  mock_apis: false
  test_data_enabled: false
  profiling_enabled: false 